services:
  postgres:
    image: postgres:18
    container_name: review_service_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reviews
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ggdevice_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d reviews"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  app:
    build: .
    container_name: review_service_app
    ports:
      - "8082:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/reviews
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - app_logs:/var/logs
    networks:
      - ggdevice_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: no

volumes:
  postgres_data:
    driver: local
  app_logs:
    driver: local

networks:
  ggdevice_network:
    external: true