server:
  port: 8082

spring:
  application:
    name: Review Service

  datasource:
    url: ${REVIEW_DB_URL}
    username: ${REVIEW_DB_USERNAME}
    password: ${REVIEW_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    vadim: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted